name: Install packages

on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download Srcml
        run: |
          wget http://131.123.42.38/lmcrs/v1.0.0/srcml_1.0.0-1_ubuntu20.04.deb

      - name: Install Srcml
        run: |
          sudo dpkg -i srcml_1.0.0-1_ubuntu20.04.deb

      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configuração do Python e Instalação de Dependências
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Ioi
        run: |
          ls

      - name: Instalação de Dependências Python
        run: |
          pip install -r requirements.txt

      - name: Verificar dependências instaladas
        run: |
          pip show pandas
